import type { AppState, Product, Seller, User } from "./types";

/** 5 gerai kantin SMK — data terisolasi per sellerId */
export const PEDAGANG = [
  {
    id: "seller_1",
    userId: "user_p1",
    username: "gerai.rpl",
    password: "rpl123",
    name: "Petugas RPL",
    stall: "GERAI RPL",
    booth: "RPL",
    phone: "",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "seller_2",
    userId: "user_p2",
    username: "gerai.br",
    password: "br123",
    name: "Petugas BR",
    stall: "GERAI BR",
    booth: "BR",
    phone: "",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "seller_3",
    userId: "user_p3",
    username: "gerai.mp",
    password: "mp123",
    name: "Petugas MP",
    stall: "GERAI MP",
    booth: "MP",
    phone: "",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "seller_4",
    userId: "user_p4",
    username: "gerai.ak",
    password: "ak123",
    name: "Petugas AK",
    stall: "GERAI AK",
    booth: "AK",
    phone: "",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "seller_5",
    userId: "user_p5",
    username: "gerai.osis",
    password: "osis123",
    name: "Petugas OSIS",
    stall: "GERAI OSIS",
    booth: "OSIS",
    phone: "",
    rating: 0,
    reviewCount: 0,
  },
] as const;

export const SELLER_ID = PEDAGANG[0].id;

const STALL_BLURB: Record<string, string> = {
  seller_1: "Gerai jurusan RPL — menu pilihan siswa SMK Negeri 17.",
  seller_2: "Gerai BR — makanan & minuman untuk istirahat siang.",
  seller_3: "Gerai MP — camilan dan menu harian kantin.",
  seller_4: "Gerai AK — makanan & snack terjangkau.",
  seller_5: "Gerai OSIS — support kegiatan siswa, menu variatif.",
};

export const DEFAULT_SELLERS: Seller[] = PEDAGANG.map((p) => ({
  id: p.id,
  name: p.stall,
  ownerUserId: p.userId,
  phone: p.phone,
  booth: p.booth,
  isActive: true,
  createdAt: Date.now(),
  description: STALL_BLURB[p.id] || "",
  rating: 0,
  reviewCount: 0,
  ratingSum: 0,
  isOpen: true,
  deliveryFee: p.id === "seller_1" ? 2000 : p.id === "seller_3" ? 3000 : 0,
}));

export const DEFAULT_USERS: User[] = [
  {
    id: "user_super",
    username: "superadmin",
    password: "super123",
    name: "Super Admin",
    role: "superadmin",
    phone: "",
    createdAt: Date.now(),
  },
  {
    id: "user_admin",
    username: "admin",
    password: "admin123",
    name: "Admin Platform",
    role: "admin",
    phone: "",
    createdAt: Date.now(),
  },
  {
    id: "user_bendahara",
    username: "bendahara",
    password: "bendahara123",
    name: "Bendahara Sekolah",
    role: "bendahara",
    phone: "",
    createdAt: Date.now(),
  },
  ...PEDAGANG.map((p) => ({
    id: p.userId,
    username: p.username,
    password: p.password,
    name: p.name,
    role: "seller" as const,
    sellerId: p.id,
    phone: p.phone,
    createdAt: Date.now(),
  })),
];

/** Crop lembut (center) — cocok object-contain di detail */
const img = (seed: string, w = 900, h = 900) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

/** Produk utama + varian — setiap varian multi punya foto sendiri */
export const DEFAULT_PRODUCTS: Product[] = [
  // ─── GERAI RPL ───
  {
    id: "prod_s1_mie",
    sellerId: "seller_1",
    canDeliver: true,
    name: "Mie",
    category: "Makanan",
    description:
      "Aneka mie goreng & kuah. Pilih varian favoritmu saat pesan.",
    image: img("photo-1569718212165-3a8278d5f624"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_mie_goreng_rendang",
        name: "Mie Goreng Rendang",
        price: 14000,
        stock: 12,
        image: img("photo-1612929633738-8fe44f7ec841"),
      },
      {
        id: "var_mie_goreng_geprek",
        name: "Mie Goreng Ayam Geprek",
        price: 15000,
        stock: 10,
        image: img("photo-1585032226651-759b368d7246"),
      },
      {
        id: "var_mie_kuah_soto",
        name: "Mie Kuah Soto",
        price: 13000,
        stock: 15,
        image: img("photo-1569718212165-3a8278d5f624"),
      },
      {
        id: "var_mie_kuah_ayam",
        name: "Mie Kuah Ayam",
        price: 13000,
        stock: 14,
        image: img("photo-1555126634-323283e090fa"),
      },
    ],
  },
  {
    id: "prod_s1_teh",
    sellerId: "seller_1",
    canDeliver: true,
    name: "Teh",
    category: "Minuman",
    description: "Teh manis/tawar, es atau anget.",
    image: img("photo-1556679343-c7306c1976bc"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_teh_es_manis",
        name: "Es Teh Manis",
        price: 4000,
        stock: 40,
        image: img("photo-1556679343-c7306c1976bc"),
      },
      {
        id: "var_teh_es_tawar",
        name: "Es Teh Tawar",
        price: 3000,
        stock: 35,
        image: img("photo-1499638673689-79a0b5115d87"),
      },
      {
        id: "var_teh_anget_manis",
        name: "Teh Anget Manis",
        price: 4000,
        stock: 25,
        image: img("photo-1571934811356-5cc061b6821f"),
      },
      {
        id: "var_teh_anget_tawar",
        name: "Teh Anget Tawar",
        price: 3000,
        stock: 20,
        image: img("photo-1544787219-7f47ccb76574"),
      },
    ],
  },
  {
    id: "prod_s1_nasgor",
    sellerId: "seller_1",
    canDeliver: true,
    name: "Nasi Goreng",
    category: "Makanan",
    description: "Nasi goreng pilihan level.",
    image: img("photo-1512058564366-18510be2db19"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_nasgor_spesial",
        name: "Nasi Goreng Spesial",
        price: 15000,
        stock: 18,
        image: img("photo-1512058564366-18510be2db19"),
      },
      {
        id: "var_nasgor_seafood",
        name: "Nasi Goreng Seafood",
        price: 18000,
        stock: 10,
        image: img("photo-1603133872878-684f208fb84b"),
      },
    ],
  },
  // ─── GERAI BR ───
  {
    id: "prod_s2_bakso",
    sellerId: "seller_2",
    canDeliver: false,
    name: "Bakso",
    category: "Makanan",
    description: "Bakso sapi kuah kaldu.",
    image: img("photo-1529042410759-befb1204b468"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_bakso_urat",
        name: "Bakso Urat Jumbo",
        price: 15000,
        stock: 18,
        image: img("photo-1529042410759-befb1204b468"),
      },
      {
        id: "var_bakso_biasa",
        name: "Bakso Biasa",
        price: 12000,
        stock: 22,
        image: img("photo-1591814468924-caf88d1232e1"),
      },
      {
        id: "var_bakso_komplit",
        name: "Bakso Komplit",
        price: 17000,
        stock: 12,
        image: img("photo-1504674900247-0877df9cc836"),
      },
    ],
  },
  {
    id: "prod_s2_mieayam",
    sellerId: "seller_2",
    canDeliver: false,
    name: "Mie Ayam",
    category: "Makanan",
    description: "Mie ayam kuah / yamin.",
    image: img("photo-1569718212165-3a8278d5f624"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_mieayam_bakso",
        name: "Mie Ayam Bakso",
        price: 14000,
        stock: 20,
        image: img("photo-1569718212165-3a8278d5f624"),
      },
      {
        id: "var_mieayam_yamin",
        name: "Mie Ayam Yamin",
        price: 14000,
        stock: 16,
        image: img("photo-1612929633738-8fe44f7ec841"),
      },
    ],
  },
  {
    id: "prod_s2_pangsit",
    sellerId: "seller_2",
    canDeliver: false,
    name: "Pangsit",
    category: "Snack",
    description: "Pangsit goreng isi ayam.",
    image: img("photo-1496116218417-1a781b1c416c"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_pangsit_5",
        name: "Pangsit Goreng (5 pcs)",
        price: 8000,
        stock: 25,
        image: img("photo-1496116218417-1a781b1c416c"),
      },
    ],
  },
  // ─── GERAI MP ───
  {
    id: "prod_s3_jeruk",
    sellerId: "seller_3",
    canDeliver: true,
    name: "Jeruk",
    category: "Minuman",
    description: "Jeruk peras segar.",
    image: img("photo-1621506289937-a8e4df240d0b"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_jeruk_es",
        name: "Es Jeruk Peras",
        price: 6000,
        stock: 30,
        image: img("photo-1621506289937-a8e4df240d0b"),
      },
      {
        id: "var_jeruk_panas",
        name: "Jeruk Hangat",
        price: 5500,
        stock: 20,
        image: img("photo-1600271886742-f049cd451bba"),
      },
    ],
  },
  {
    id: "prod_s3_coklat",
    sellerId: "seller_3",
    canDeliver: true,
    name: "Coklat",
    category: "Minuman",
    description: "Coklat susu.",
    image: img("photo-1517578239113-b03992cec17b"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_coklat_es",
        name: "Es Coklat",
        price: 7000,
        stock: 28,
        image: img("photo-1517578239113-b03992cec17b"),
      },
      {
        id: "var_coklat_panas",
        name: "Coklat Hangat",
        price: 7000,
        stock: 15,
        image: img("photo-1542990253-0d0f5be5f0ed"),
      },
    ],
  },
  {
    id: "prod_s3_air",
    sellerId: "seller_3",
    canDeliver: true,
    name: "Air Mineral",
    category: "Minuman",
    description: "Air mineral botol.",
    image: img("photo-1548839140-29a749e1cf4d"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_air_600",
        name: "Air Mineral 600ml",
        price: 3500,
        stock: 80,
        image: img("photo-1548839140-29a749e1cf4d"),
      },
    ],
  },
  // ─── GERAI AK ───
  {
    id: "prod_s4_risoles",
    sellerId: "seller_4",
    canDeliver: false,
    name: "Risoles",
    category: "Snack",
    description: "Risoles renyah isi pilihan.",
    image: img("photo-1601050690597-df0568f70950"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_risoles_mayo",
        name: "Risoles Mayo",
        price: 5000,
        stock: 16,
        image: img("photo-1601050690597-df0568f70950"),
      },
      {
        id: "var_risoles_ragout",
        name: "Risoles Ragout",
        price: 5500,
        stock: 12,
        image: img("photo-1626082927389-6cd097cdc6ec"),
      },
    ],
  },
  {
    id: "prod_s4_pisang",
    sellerId: "seller_4",
    canDeliver: false,
    name: "Pisang Goreng",
    category: "Snack",
    description: "Pisang goreng isi.",
    image: img("photo-1587132137056-bfbf0166836e"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_pisang_coklat",
        name: "Pisang Goreng Coklat",
        price: 6000,
        stock: 20,
        image: img("photo-1587132137056-bfbf0166836e"),
      },
      {
        id: "var_pisang_keju",
        name: "Pisang Goreng Keju",
        price: 7000,
        stock: 14,
        image: img("photo-1488477181946-6428a0291777"),
      },
    ],
  },
  {
    id: "prod_s4_keripik",
    sellerId: "seller_4",
    canDeliver: false,
    name: "Keripik",
    category: "Snack",
    description: "Keripik renyah.",
    image: img("photo-1566478989037-eec170784d0b"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_keripik_kentang",
        name: "Keripik Kentang",
        price: 5000,
        stock: 40,
        image: img("photo-1566478989037-eec170784d0b"),
      },
    ],
  },
  // ─── GERAI OSIS ───
  {
    id: "prod_s5_nasi",
    sellerId: "seller_5",
    canDeliver: false,
    name: "Nasi",
    category: "Makanan",
    description: "Nasi rames & lauk harian.",
    image: img("photo-1546069901-ba9599a7e63c"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_nasi_rames",
        name: "Nasi Rames Lengkap",
        price: 13000,
        stock: 30,
        image: img("photo-1546069901-ba9599a7e63c"),
      },
      {
        id: "var_nasi_uduk",
        name: "Nasi Uduk Komplit",
        price: 14000,
        stock: 18,
        image: img("photo-1516684669134-de6f7c473a2a"),
      },
    ],
  },
  {
    id: "prod_s5_ayam",
    sellerId: "seller_5",
    canDeliver: false,
    name: "Ayam",
    category: "Makanan",
    description: "Ayam goreng / geprek.",
    image: img("photo-1626082927389-6cd097cdc6ec"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_ayam_geprek",
        name: "Ayam Geprek Sambal",
        price: 16000,
        stock: 15,
        image: img("photo-1626082927389-6cd097cdc6ec"),
      },
      {
        id: "var_ayam_goreng",
        name: "Ayam Goreng Krispi",
        price: 15000,
        stock: 12,
        image: img("photo-1598103442097-8b74394b95c6"),
      },
    ],
  },
  {
    id: "prod_s5_soto",
    sellerId: "seller_5",
    canDeliver: false,
    name: "Soto",
    category: "Makanan",
    description: "Soto hangat.",
    image: img("photo-1582878826629-29b7ad1cdc43"),
    isActive: true,
    createdAt: Date.now(),
    variants: [
      {
        id: "var_soto_ayam",
        name: "Soto Ayam",
        price: 12000,
        stock: 14,
        image: img("photo-1582878826629-29b7ad1cdc43"),
      },
    ],
  },
];

export function createInitialState(): AppState {
  return {
    users: DEFAULT_USERS,
    sellers: DEFAULT_SELLERS,
    products: DEFAULT_PRODUCTS,
    orders: [],
    settings: {
      schoolName: "SMK Negeri 17",
      commissionRate: 7,
      platformWhatsapp: "6285810383881",
      withdrawalFeeType: "percent",
      withdrawalFeeValue: 3,
      menuCategories: ["Makanan", "Minuman", "Snack"],
      announcements: [],
      operatingHours: {
        enabled: false,
        openTime: "06:30",
        closeTime: "16:00",
      },
      enabledPaymentMethods: ["online", "canteen"],
      activityLog: [],
    },
    cart: [],
    session: null,
    orderSeq: 0,
    reviews: [],
    withdrawals: [],
    autoPayouts: {},
    salesReports: [],
  };
}
